version: '3.8'

services:
  spring-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}